apiVersion: v2
name: auto-blackbox-exporter
description: Auto generate a prometheus scrape config for existing Ingress objects. Includes Uptime and SSL Certificate Expiry Alerts.
type: application
version: 0.1.0
appVersion: "1.16.0"
