{{ $ingressList := (include "blackbox.ingress" . | fromYaml) -}}
{{- if $ingressList}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blackbox.name" .}}-scrape-config 
  labels:
    {{- include "blackbox.prometheus-additional-scrape-config-labels" . | nindent 4 }}
    {{- include "blackbox.selectorLabels" . | nindent 4 }}
stringData:
  {{ .Values.configObjKeyName }}: |-
    - job_name: {{ .Values.prometheusJobName }}
      metrics_path: /probe 
      params:
        module: [http_2xx] # Send a "module" HTTP parameter to the exporter to select the right probe module.
      static_configs:
        - targets:
          {{- if $ingressList.hosts }}
          {{- toYaml $ingressList.hosts | nindent 10 }}
          {{- else }}
          - error--you-have-no-ingress-objects.auto-blackbox-exporter.io
          {{- end }}
      relabel_configs:
        # Set the "target" HTTP parameter to the target URL that we want to probe.
        - source_labels: [__address__]
          target_label: __param_target
        # Set the "instance" label to the target URL that we want to probe.
        - source_labels: [__param_target]
          target_label: instance
        # Don't actually scrape the target itself, but the Blackbox Exporter.
        - target_label: __address__
          replacement: {{ (include "blackbox.blackbox-service-endpoint" . | fromYaml).uri }} 
{{- end }}